package handlers

import (
	"context"
	"net/http"
	"time"

	"github.com/danielgtaylor/huma/v2"
)

// Register attaches every server route to the given huma.API. It is the
// single source of truth for the REST surface — the OpenAPI spec
// generated by huma reflects exactly the operations registered here.
func Register(api huma.API, cal *ScopedCalendarHandler, rem *ScopedRemindersHandler) {
	registerHealth(api)
	registerReady(api, cal)
	registerCalendarRoutes(api, cal)
	registerEventRoutes(api, cal)
	registerListRoutes(api, rem)
	registerReminderRoutes(api, rem)
}

// HealthResponse reports process liveness.
type HealthResponse struct {
	Body struct {
		Status string `json:"status" enum:"ok"`
	}
}

func registerHealth(api huma.API) {
	huma.Register(api, huma.Operation{
		OperationID: "healthcheck",
		Method:      "GET",
		Path:        "/healthz",
		Summary:     "Liveness probe — returns ok as long as the process is up.",
		Tags:        []string{"meta"},
	}, func(ctx context.Context, _ *struct{}) (*HealthResponse, error) {
		out := &HealthResponse{}
		out.Body.Status = "ok"
		return out, nil
	})
}

// ReadyResponse reports bridge readiness.
type ReadyResponse struct {
	Body struct {
		Status string `json:"status" enum:"ready"`
	}
}

// readinessTimeout caps the EventKit ping done inside /readyz so a
// stuck bridge can't hang the probe.
const readinessTimeout = 2 * time.Second

// registerReady wires /readyz which actually pings EventKit (via the
// scoped calendar's Calendars()) to confirm the cgo bridge is alive and
// TCC permissions are still valid. 503 if it fails — useful for
// orchestrators that may need to know "this process is up but its
// dependencies are not."
func registerReady(api huma.API, cal *ScopedCalendarHandler) {
	huma.Register(api, huma.Operation{
		OperationID: "readiness",
		Method:      "GET",
		Path:        "/readyz",
		Summary:     "Readiness probe — pings EventKit to confirm the bridge is alive.",
		Tags:        []string{"meta"},
	}, func(ctx context.Context, _ *struct{}) (*ReadyResponse, error) {
		probeCtx, cancel := context.WithTimeout(ctx, readinessTimeout)
		defer cancel()
		_ = probeCtx
		if _, err := cal.S.Calendars(); err != nil {
			return nil, huma.NewError(http.StatusServiceUnavailable, "bridge unhealthy: "+err.Error())
		}
		out := &ReadyResponse{}
		out.Body.Status = "ready"
		return out, nil
	})
}
