// Command bundle-app wraps a built Go binary in a minimal macOS .app
// bundle so the system's TCC dialog attribution and usage descriptions
// work the way they do for a Swift/Xcode app.
//
// Why this exists: a bare CLI executable run from a terminal is
// attributed to the parent terminal for Privacy & Security purposes,
// and macOS 14+ silently denies access without a usage-description
// string in the Info.plist. Wrapping the binary in a .app with proper
// NSCalendarsUsageDescription / NSRemindersUsageDescription strings
// makes the system pop the familiar TCC dialog the first time the
// binary asks for Calendar/Reminders access.
//
// Usage:
//
//	go build -o /tmp/eventkit-server ./cmd/eventkit-server
//	go run ./cmd/bundle-app --bin /tmp/eventkit-server --out /tmp/Eventkit.app
//	/tmp/Eventkit.app/Contents/MacOS/Eventkit --listen 127.0.0.1:8787
//
// The bundle is ad-hoc signed with `codesign --sign -` by default so
// macOS treats it as a stable identity for TCC purposes (so the user's
// "Allow" decision sticks across runs).
package main

import (
	"bytes"
	"encoding/xml"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	buildVersion "github.com/dillonbrowne/go-eventkit/internal/version"
)

const infoPlistTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleIdentifier</key><string>{{.BundleID | xml}}</string>
	<key>CFBundleName</key><string>{{.Name | xml}}</string>
	<key>CFBundleDisplayName</key><string>{{.Name | xml}}</string>
	<key>CFBundleExecutable</key><string>{{.Name | xml}}</string>
	<key>CFBundlePackageType</key><string>APPL</string>
	<key>CFBundleShortVersionString</key><string>{{.Version | xml}}</string>
	<key>CFBundleVersion</key><string>{{.Version | xml}}</string>
	<key>LSMinimumSystemVersion</key><string>14.0</string>
{{- if .Background}}
	<key>LSUIElement</key><true/>
{{- end}}
{{- if .CalDesc}}
	<key>NSCalendarsUsageDescription</key><string>{{.CalDesc | xml}}</string>
{{- end}}
{{- if .RemDesc}}
	<key>NSRemindersUsageDescription</key><string>{{.RemDesc | xml}}</string>
{{- end}}
	<key>NSHumanReadableCopyright</key><string>Generated by go-eventkit bundle-app</string>
</dict>
</plist>
`

type plistData struct {
	Name       string
	BundleID   string
	Version    string
	CalDesc    string
	RemDesc    string
	Background bool
}

func main() {
	var (
		bin        = flag.String("bin", "", "Path to the built binary (required).")
		name       = flag.String("name", "", "App name. Defaults to a Title-cased binary basename.")
		bundleID   = flag.String("bundle-id", "", "CFBundleIdentifier. Defaults to dev.local.<lowercase-name>.")
		out        = flag.String("out", "", "Output .app path. Defaults to <bin-dir>/<Name>.app.")
		version    = flag.String("version", buildVersion.Version, "CFBundleShortVersionString and CFBundleVersion. Defaults to the ldflags-injected internal/version.Version.")
		calDesc    = flag.String("cal-desc", "go-eventkit exposes macOS Calendar over a localhost REST API.", "NSCalendarsUsageDescription. Empty disables the key.")
		remDesc    = flag.String("rem-desc", "go-eventkit exposes macOS Reminders over a localhost REST API.", "NSRemindersUsageDescription. Empty disables the key.")
		background = flag.Bool("background", true, "Set LSUIElement=true so the app does not appear in the Dock.")
		sign       = flag.Bool("sign", true, "Ad-hoc codesign the bundle (`codesign --sign -`). Required on macOS for TCC to attribute the prompt to the bundle.")
	)
	flag.Parse()

	if *bin == "" {
		fail("--bin is required (path to a built binary)")
	}

	if *name == "" {
		*name = deriveName(*bin)
	}
	if *bundleID == "" {
		*bundleID = "dev.local." + strings.ToLower(*name)
	}
	if *out == "" {
		*out = filepath.Join(filepath.Dir(*bin), *name+".app")
	}

	if err := bundle(*bin, *out, plistData{
		Name:       *name,
		BundleID:   *bundleID,
		Version:    *version,
		CalDesc:    *calDesc,
		RemDesc:    *remDesc,
		Background: *background,
	}, *sign); err != nil {
		fail(err.Error())
	}

	fmt.Printf("bundled %s → %s\n", *bin, *out)
	fmt.Printf("run with: %s/Contents/MacOS/%s [flags]\n", *out, *name)
}

func deriveName(bin string) string {
	base := filepath.Base(bin)
	ext := filepath.Ext(base)
	stem := base[:len(base)-len(ext)]
	if stem == "" {
		fail("could not derive --name from --bin %q; pass --name explicitly", bin)
	}
	// Title-case the first letter to look like an app name. macOS treats
	// CFBundleExecutable case-sensitively, so we keep the rest of the
	// stem unchanged.
	return strings.ToUpper(stem[:1]) + stem[1:]
}

func bundle(bin, out string, data plistData, sign bool) error {
	fi, err := os.Stat(bin)
	if err != nil {
		return fmt.Errorf("stat --bin: %w", err)
	}
	if fi.IsDir() {
		return fmt.Errorf("--bin must be a regular file, not %q", bin)
	}

	// Idempotent: wipe any prior bundle at this path.
	if err := os.RemoveAll(out); err != nil {
		return fmt.Errorf("remove existing %q: %w", out, err)
	}

	macOSDir := filepath.Join(out, "Contents", "MacOS")
	if err := os.MkdirAll(macOSDir, 0o755); err != nil {
		return fmt.Errorf("mkdir Contents/MacOS: %w", err)
	}

	if err := copyFile(bin, filepath.Join(macOSDir, data.Name), 0o755); err != nil {
		return fmt.Errorf("copy binary: %w", err)
	}

	plistPath := filepath.Join(out, "Contents", "Info.plist")
	if err := writePlist(plistPath, data); err != nil {
		return fmt.Errorf("write Info.plist: %w", err)
	}

	if sign {
		if err := codesign(out); err != nil {
			return fmt.Errorf("codesign: %w", err)
		}
	}
	return nil
}

func writePlist(path string, data plistData) error {
	funcs := template.FuncMap{"xml": xmlEscape}
	tmpl, err := template.New("plist").Funcs(funcs).Parse(infoPlistTemplate)
	if err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return tmpl.Execute(f, data)
}

func xmlEscape(s string) string {
	var buf bytes.Buffer
	if err := xml.EscapeText(&buf, []byte(s)); err != nil {
		return s
	}
	return buf.String()
}

func copyFile(src, dst string, perm os.FileMode) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, perm)
	if err != nil {
		return err
	}
	defer out.Close()
	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Close()
}

func codesign(bundlePath string) error {
	cmd := exec.Command("codesign", "--force", "--deep", "--sign", "-", bundlePath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "bundle-app: "+format+"\n", args...)
	os.Exit(1)
}
