#!/usr/bin/env bash
#
# make-policy.sh — generate a deny-by-default eventkit-server policy that
# allows readwrite on specific calendars / reminder lists, looked up by
# TITLE. Calendar and list identifiers are per-iCloud-account UUIDs, so a
# policy can't be copied between machines; this script discovers the
# right IDs on the machine it runs on.
#
# It spins up a TEMPORARY eventkit-server with a permissive read-only
# policy on a scratch port, lists calendars + lists, resolves the titles
# you ask for into IDs, writes the scoped policy, and shuts the temp
# server down. Requires: eventkit-server on PATH (or --bin), Calendar +
# Reminders TCC access already granted to that binary, python3, curl.
#
# Usage:
#   scripts/make-policy.sh --calendar testing --list testing --out ~/.config/eventkit/policy.yaml
#   scripts/make-policy.sh --calendar Work --calendar Personal --list Todo --out policy.yaml
#
set -euo pipefail

bin="eventkit-server"
out=""
port="8799"
calendars=()
lists=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --calendar) calendars+=("$2"); shift 2 ;;
    --list)     lists+=("$2"); shift 2 ;;
    --out)      out="$2"; shift 2 ;;
    --bin)      bin="$2"; shift 2 ;;
    --port)     port="$2"; shift 2 ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$out" ]]; then echo "error: --out is required" >&2; exit 2; fi
if [[ ${#calendars[@]} -eq 0 && ${#lists[@]} -eq 0 ]]; then
  echo "error: pass at least one --calendar or --list" >&2; exit 2
fi

base="http://127.0.0.1:${port}"
tmp_policy="$(mktemp -t evk-discover).yaml"
printf 'calendar:\n  default: read\nreminders:\n  default: read\n' > "$tmp_policy"

cleanup() {
  [[ -n "${server_pid:-}" ]] && kill "$server_pid" 2>/dev/null || true
  rm -f "$tmp_policy"
}
trap cleanup EXIT

echo "Starting temporary read-only server on ${base} ..." >&2
"$bin" --listen "127.0.0.1:${port}" --policy "$tmp_policy" >/dev/null 2>&1 &
server_pid=$!

# Wait for readiness (bridge reachable = TCC granted).
ready=""
for _ in $(seq 1 30); do
  if curl -fsS "${base}/readyz" >/dev/null 2>&1; then ready=1; break; fi
  sleep 0.3
done
if [[ -z "$ready" ]]; then
  echo "error: server did not become ready. Is TCC granted for ${bin}?" >&2
  echo "       Run '${bin} --listen 127.0.0.1:${port}' once in a terminal and click Allow." >&2
  exit 1
fi

cals_json="$(curl -fsS "${base}/v1/calendars")"
lists_json="$(curl -fsS "${base}/v1/lists")"

# resolve_title <json> <collection-key> <title> -> prints id or errors.
# JSON arrives on stdin (herestring); key+title are argv so quoting in
# titles is safe.
resolve_title() {
  python3 -c '
import sys, json
key, want = sys.argv[1], sys.argv[2].strip().lower()
data = json.loads(sys.stdin.read())
matches = [x["id"] for x in data[key] if x["title"].strip().lower() == want]
if len(matches) == 0:
    sys.stderr.write("error: no %s titled %r found\n" % (key[:-1], sys.argv[2])); sys.exit(1)
if len(matches) > 1:
    sys.stderr.write("error: %d %s titled %r; titles must be unique\n" % (len(matches), key, sys.argv[2])); sys.exit(1)
print(matches[0])
' "$2" "$3" <<<"$1"
}

cal_ids=()
for title in "${calendars[@]}"; do
  cal_ids+=("$(resolve_title "$cals_json" calendars "$title")")
done
list_ids=()
for title in "${lists[@]}"; do
  list_ids+=("$(resolve_title "$lists_json" lists "$title")")
done

mkdir -p "$(dirname "$out")"
{
  echo "# Generated by scripts/make-policy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Deny-by-default; only the listed calendars / reminder lists are readwrite."
  echo "calendar:"
  echo "  default: deny"
  if [[ ${#cal_ids[@]} -gt 0 ]]; then
    echo "  allow:"
    for i in "${!cal_ids[@]}"; do
      echo "    - id: ${cal_ids[$i]}        # ${calendars[$i]}"
      echo "      mode: readwrite"
    done
  fi
  echo "reminders:"
  echo "  default: deny"
  if [[ ${#list_ids[@]} -gt 0 ]]; then
    echo "  allow:"
    for i in "${!list_ids[@]}"; do
      echo "    - list_id: ${list_ids[$i]}   # ${lists[$i]}"
      echo "      mode: readwrite"
    done
  fi
} > "$out"

echo "Wrote ${out}:" >&2
echo "---" >&2
cat "$out" >&2